version: "3.9"
services:
  lfs:
    build: .
    volumes:
      - "./logs:/mnt/lfs/logs" # Use LFS locations because the chroot env is not aware of the parent dirs
      - "./output:/mnt/lfs/output"
    privileged: true
